version: "3.9"

volumes:
  hosts_config:
    driver: local
    driver_opts:
      type: none
      device: ${SITES_PATH}
      o: bind

services:
  mtdelog-nacos:
    image: nacos/nacos-server:latest
    container_name: mtdelog-nacos
    hostname: mtdelog-nacos.org
    privileged: true
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=172.16.0.20
      - MYSQL_SERVICE_DB_NAME=mtdelog_nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=mtdelog@2023
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
      - NACOS_AUTH_ENABLE=true
      #- NACOS_AUTH_TOKEN=GodAMZDPU6VLjNsbFqiSEKrT2t7Opl5g
      - NACOS_AUTH_TOKEN=R29kQU1aRFBVNlZMak5zYkZxaVNFS3JUMnQ3T3BsNWc=
      - NACOS_AUTH_IDENTITY_KEY=mtdelog-nacos
      - NACOS_AUTH_IDENTITY_VALUE=mtdelog-nacos
      - JVM_XMS=256m
      - JVM_XMX=256m
      - JVM_MS=128m
      - JVM_MMS=128m
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/nacos/logs/:/home/nacos/logs
      - /usr/deploys/mnt/nacos/init.d:/home/nacos/init.d
    depends_on:
      - mtdelog-mysql
    ports:
      - 8848:8848
      - 9848:9848
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.60
    restart: always

  mtdelog-redis:
    image: wjlmgqs/mtdelog-redis:1.0
    container_name: mtdelog-redis
    hostname: mtdelog-redis.org
    environment:
      - TZ=Asia/Shanghai
      - requirepass=mtdelog@2023
    ports:
      - 6379:6379
    command: ["redis-server","/etc/redis/redis.conf"]
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/redis/redis.conf:/etc/redis/redis.conf
      - /usr/deploys/mnt/redis/data:/data
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.50
    restart: always

  mtdelog-rabbitmq:
    image: wjlmgqs/mtdelog-rabbitmq:1.0
    container_name: mtdelog-rabbitmq
    hostname: mtdelog-rabbitmq.org
    volumes:
      - ${SITES_PATH}:/etc/sites
    ports:
      - 15672:15672
      - 5672:5672
      - 25672:25672
      - 61613:61613
      - 1883:1883
    environment:
      - RABBITMQ_DEFAULT_USER=mtdev
      - RABBITMQ_DEFAULT_PASS=mt@2023#dev
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.40
    restart: always

  mtdelog-minio:
    image: wjlmgqs/mtdelog-minio:1.0
    container_name: mtdelog-minio
    hostname: mtdelog-minio.org
    environment:
      - MINIO_SERVER_HOST=minio
      - MINIO_ROOT_USER=miniodev
      - MINIO_ROOT_PASSWORD=minio@2023#dev
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/minio/data:/data
      - /usr/deploys/mnt/minio/config:/root/.minio
    command: server /data --console-address ":9001"
    ports:
      #容器间访问，不需要指定端口
      - 9000:9000
      - 9001:9001
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.30
    restart: always

  mtdelog-mysql:
    image: wjlmgqs/mtdelog-mysql:1.0
    container_name: mtdelog-mysql
    hostname: mtdelog-mysql.org
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=mtdelog@2023
      - TZ=Asia/Shanghai
    #command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/mysql/log:/var/log/mysql
      - /usr/deploys/mnt/mysql/data:/var/lib/mysql
      - /usr/deploys/mnt/mysql/conf:/etc/mysql/conf.d
    ports:
      - 3306:3306
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.20
    restart: always

networks:
  mtdelog-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
