server:
  servlet:
    contextPath: /nacos
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i'
    basedir: 'logs'
spring:
  datasource:
    platform: mysql
db:
  num: 1
  #password:
  #  '0': ${MYSQL-PWD:root}
  #url:
  #  '0': jdbc:mysql://${MYSQL-HOST:jeecg-boot-mysql}:${MYSQL-PORT:3307}/${MYSQL-DB:mtdelog_nacos}?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  #user:
  #  '0': ${MYSQL-USER:root}
  url:
    '0': jdbc:mysql://${MYSQL-HOST:mtdelog-mysql.org}:${MYSQL-PORT:3306}/${MYSQL-DB:mtdelog_nacos}?characterEncoding=utf8&connectTimeout=10000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  user: ${MYSQL-PWD:root}
  password: ${MYSQL-USER:mtdelog@2023}

management:
  metrics:
    export:
      elastic:
        enabled: false
      influx:
        enabled: false
nacos:
  core:
    auth:
      #是否开启鉴权（JeecgNacosApplication.enabled属性优先级更高）
      enabled: false
      caching:
        enabled: true
      server:
        identity:
          key: mtdelog-nacos
          value: mtdelog-nacos
      plugin:
        nacos:
          token:
            expire:
              seconds: 18000
            secret:
              key: R29kQU1aRFBVNlZMak5zYkZxaVNFS3JUMnQ3T3BsNWc=
      system:
        type: nacos
  istio:
    mcp:
      server:
        enabled: false
  naming:
    empty-service:
      auto-clean: true
      clean:
        initial-delay-ms: 50000
        period-time-ms: 30000
  security:
    ignore:
      urls: /,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
  #standalone: true