jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: database
      data-id: jeecg-gateway-router
spring:
  redis:
    database: 1
    host: mtdelog-redis.org
    port: 6379
    password: mtdelog@2023