jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: database
      group: DEFAULT_GROUP
      data-id: jeecg-gateway-router
spring:
  redis:
    database: 1
    host: jeecg-boot-redis
    port: 6388
    password: mtdelog@2023