version: "3.9"

volumes:
  hosts_config:
    driver: local
    driver_opts:
      type: none
      device: ${SITES_PATH}
      o: bind
services:
  mtdelog-boot:
    container_name: mtdelog-boot
    hostname: mtdelog-boot.org
    ports:
      - 17001:7001
    build:
      context: ./docker-boot
    restart: on-failure
    environment:
      - JVM_XMS=128m
      - JVM_XMX=128m
      - JVM_MS=64m
      - JVM_MMS=64m
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/boot/logs:/root/logs/csp
    extra_hosts:
      - "mtdelog-mysql.org:122.51.217.92"
      - "mtdelog-minio.org:122.51.217.92"
      - "mtdelog-rabbitmq.org:122.51.217.92"
      - "mtdelog-redis.org:122.51.217.92"
      - "mtdelog-nacos.org:122.51.217.92"
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.200

  mtdelog-sentinel:
    container_name: mtdelog-sentinel
    hostname: mtdelog-sentinel.org
    ports:
      - 19000:9000
    build:
      context: ./docker-sentinel
    restart: on-failure
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/sentinel/logs:/root/logs/csp
    extra_hosts:
      - "mtdelog-nacos.org:122.51.217.92"
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.90

  mtdelog-gateway:
    container_name: mtdelog-gateway
    hostname: mtdelog-gateway.org
    ports:
      - 19999:9999
    build:
      context: ./docker-gateway
    restart: on-failure
    mem_limit: 320m
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/gateway/logs:/root/logs/csp
    extra_hosts:
      - "mtdelog-mysql.org:122.51.217.92"
      - "mtdelog-minio.org:122.51.217.92"
      - "mtdelog-rabbitmq.org:122.51.217.92"
      - "mtdelog-redis.org:122.51.217.92"
      - "mtdelog-nacos.org:122.51.217.92"
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.80

  mtdelog-nginx:
    image: wjlmgqs/mtdelog-nginx:1.0
    container_name: mtdelog-nginx
    hostname: mtdelog-nginx.org
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ${SITES_PATH}:/etc/sites
      - /usr/deploys/mnt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/deploys/mnt/nginx/conf/conf.d:/etc/nginx/conf.d
      - /usr/deploys/mnt/nginx/logs:/var/log/nginx
      - /usr/deploys/envs/html:/usr/share/nginx/html
      - /usr/deploys/mnt/nginx/cert:/etc/nginx/cert
    ports:
      - 80:80
      - 443:443
    #network_mode: host
    extra_hosts:
      - "mtdelog-gateway.org:172.16.0.80"
      - "mtdelog-boot.org:172.16.0.200"
    networks:
      mtdelog-network:
        ipv4_address: 172.16.0.11
    restart: always

networks:
  mtdelog-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
